### ISSUE TITLE
Sed Zone bug in register.sh

### ISSUE THREAD

**Issue by Yamakasi** [antevens/letsencrypt-freeipa#10]
Hi,

Refering to #9 

https://github.com/antevens/letsencrypt-freeipa/blob/662e4df4a8eeb0dd938e42c4e01e79eb8ecfbcc0/register.sh#L112

`zone="$(echo "${principal}" | sed -e 's/^[a-zA-Z0-9\-\_]*\.//')" `

needs to be:

`zone="$(echo "${principal}" | sed -e 's/^[a-zA-Z0-9_-]*\.//')"`

After this I still end up at:

```
Keytab successfully retrieved and stored in: /etc/lets-encrypt.keytab
  Record name: _acme-challenge.ipa-01-dc-01
  TXT record: INITIALIZED
Loaded config parameter realm with value of 'IPA.DOMAIN.TLD'
kinit: Preauthentication failed while getting initial credentials
```

Thanks so far!

**Comment by antevens** [comment]
Thx, check out the changes in the develop branch if you have time and I'm happy to accept Pull/Merge requests :)

**Comment by Yamakasi** [comment]
@antevens Will do, I also see some keytab issues for the lets encrypt keytab, maybe it's fixed there :)

Can you update the readme for this dev usage as well ? 

I will test the "hell" out of it, PR's are not my thing really ;)
