### ISSUE TITLE
FreeIPA 4.6.4

### ISSUE THREAD

**Issue by Yamakasi** [antevens/letsencrypt-freeipa#11]
Hi,

As the automation of this is pretty nice but needs some work I would like to know if you have tested the development version on 4.6.4 ?

I get various errors where I'm not sure what has been done/changed/optimized.

Thanks for the great work so far!

Cheers

**Comment by antevens** [comment]
Like I said, it's untested, I don't have the resources/time to validate and test all of this right now and so I'll keep it in the develop branch until that time.
