### ISSUE TITLE
Landing page is still showing "Connection not secure"

### ISSUE THREAD

**Issue by amohideen** [antevens/letsencrypt-freeipa#20]
I tested the code on freeipa v:4.8.6, I ran the ./install, however, the landing page is still showing the Connection not secure with a yellow triangle in the browser bar. Am I missing anything?
also broke at line 88 with  
bash: line 88: syntax error near unexpected token `}'

I think it is in the register.sh?

**Comment by antevens** [comment]
Sorry about the late response.

Just to confirm:

You downloaded or installed the scripts and then you ran register.sh and got  the error above, any more messages or errors?
