### ISSUE TITLE
Syntax Error after wget command

### ISSUE THREAD

**Issue by n1ete** [antevens/letsencrypt-freeipa#3]
i get an
`bash: line 50: syntax error near unexpected token `}'`

when i throw as root user an 
`wget https://raw.githubusercontent.com/antevens/letsencrypt-freeipa/master/install.sh -O - | bash`
in the terminal?

any idea why?
thanks btw for this amazing script

**Comment by liilac** [comment]
I have no idea why but for some reason piping `wget` output to `bash` isn't working for the scripts in this repo.

I was able to get this to work by cloning the repo and using those scripts, and editing https://github.com/antevens/letsencrypt-freeipa/blob/master/install.sh#L57 to read `bash ./register.sh`.  Note that this will obviously mean you need to `chdir` into where you cloned the repo.

You could alternatively just download https://github.com/antevens/letsencrypt-freeipa/blob/master/install.sh and edit the line I mentioned above to download the file and then execute it rather than piping the output, and then execute that.

**Comment by antevens** [comment]
Sorry for not responding earlier, my GitHub notification settings were not correctly set.

Is it possible you were behind a proxy or some other device or were somehow getting corrupted data?

**Comment by nicolas-b12** [comment]
Hello,

I try to run this script in a basic AWS environment and I get this error too... Nothing fancy with proxy and so.

**Comment by antevens** [comment]
I'll have to look into it when I get time and try to see if more logging can be added, if you have any more info or debug texts that would help.

**Comment by maverick85** [comment]
Hi,

I just came across this issue.
My FreeIPA server is not behind a proxy of any sort. I logged into the server via ssh with root, and used kinit admin to get a valid kerberos ticket.

Then I ran the command:

```
[root@ipa ~]# wget https://raw.githubusercontent.com/antevens/letsencrypt-freeipa/master/install.sh -O - | bash
--2019-05-27 20:49:05--  https://raw.githubusercontent.com/antevens/letsencrypt-freeipa/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2785 (2.7K) [text/plain]
Saving to: ‘STDOUT’

100%[====================================================================================================================================================================================================================================================================================>] 2,785       --.-K/s   in 0s      

2019-05-27 20:49:05 (28.0 MB/s) - written to stdout [2785/2785]





bash: line 51: syntax error near unexpected token `}'
[root@ipa ~]#
```

I will try the proposed work-around to get it installed.

Running FreeIPA 4.6.4 on CentOS 7.6

**Comment by antevens** [comment]
Hi n1ete, 

Downloading it by hand or using curl is probably the best workaround.

**Comment by maverick85** [comment]
Hi @antevens 

thank you for your quick reply. I had opened an issue (#15) in case you want to keep track of this issue because this was closed.
I confirm that by downloading, editing line 58 with ./register and running ./install.sh all works perfectly.

Thank you for this!
