### ISSUE TITLE
kinit: Preauthentication failed while getting initial credentials

### ISSUE THREAD

**Issue by Piping** [antevens/letsencrypt-freeipa#6]
Hi,

after running the command, the register stop at renew script 

```shell
+ [[ '' =~ ^[^#]*= ]]
+ read line
++ hostname
+ host=m1.freeipa.sxl.io
+ kinit -k -t /etc/lets-encrypt.keytab lets-encrypt/master.freeipa.example.com
kinit: Preauthentication failed while getting initial credentials
```

Any Help?

**Comment by antevens** [comment]
Hey sorry for the late reply, I missed the notifications.

Are you still having an issue with this?

**Comment by Piping** [comment]
@antevens Hi, I left this issue behind for now. If I encounter it again, I will repoen the issue
