### ISSUE TITLE
ipa: DNS Zone not found

### ISSUE THREAD

**Issue by Yamakasi** [antevens/letsencrypt-freeipa#9]
To update this wit some issues people might want to run into:

What can cause:

```
Keytab successfully retrieved and stored in: /etc/lets-encrypt.keytab
ipa: ERROR: ipa-01-dc-01.mydomain.net: DNS zone not found

```

This happens on a fresh install of Freeipa.

_I this fails we might want to skip the principals-add on a rerun, maybe you have an idea for checks there._

**Comment by antevens** [comment]
Thanks,

I've already added a note as the second paragraph of the README that states that FreeIPA needs to manage the DNS domain and the server(s) have to be authorative.

**Comment by Yamakasi** [comment]
Good thanks!

The issue is, they are, there are no other servers that host this subdomain, I run them in an .ipa. subdomain which I removed *ABOVE* by accident.

**Comment by Yamakasi** [comment]
Any update from you on this ? A fresh installed IPA server in a subdomain should be authorative for the domain, so to say subdomain. Or so we need the domain itself with gluerecords ?

**Comment by antevens** [comment]
Hi Yamakasi,

Perhaps you can check out the code in the develop branch, it's got a number of fixes for subdomains and even allows 3rd party DNS servers. Note that I have not fully tested the code so it's all experimental.

**Comment by antevens** [comment]
I think these should be fixed with the latest changes, it you get a chance please confirm and re-open this issue if you still have issues.
